services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=peopledb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodejs-challenge-network

  nodejs:
    build: 
      context: ./nodejs
      dockerfile: Dockerfile
    image: mmcarvaxd/nodejs:prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh index.js
    networks: 
      - nodejs-challenge-network
    volumes: 
      - ./nodejs:/usr/src/app
    tty: true
    depends_on: 
       - db

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: mmcarvaxd/nginx:prod
    container_name: nginx
    networks:
      - nodejs-challenge-network
    ports:
      - "8080:80"
    
networks: 
  nodejs-challenge-network:
    driver: bridge      
